# mysql datasource
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mch?characterEncoding=utf-8
#    username: root
#    password: OUnT17i/OgatVZCDu9xSUIRn566x/ojv5NBGgnOolAGZz+sB9PGXK6mbmUmtnBT5Sf3Y4w9Z3NUQUmo1H6Oe4w==
    driverClassName: com.mysql.jdbc.Driver
    #集成alibaba的druid
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,config,slf4j
      maxActive: 20
      initialSize: 2
      maxWait: 60000
      minIdle: 2
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPi2MeUBRahrFZgtNCU8rYdsADOJxnUJMsRV4pnZzXA2rgUI89ILgWiJx8kspbwWHg/kMTQZSZWgoVIaFvRuokCAwEAAQ==

---
## production environment setting
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mch?characterEncoding=utf-8
    username: root
    password: OUnT17i/OgatVZCDu9xSUIRn566x/ojv5NBGgnOolAGZz+sB9PGXK6mbmUmtnBT5Sf3Y4w9Z3NUQUmo1H6Oe4w==
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPi2MeUBRahrFZgtNCU8rYdsADOJxnUJMsRV4pnZzXA2rgUI89ILgWiJx8kspbwWHg/kMTQZSZWgoVIaFvRuokCAwEAAQ==

---
## testing environment setting
spring:
  profiles: beta
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mch?characterEncoding=utf-8
    username: root1
    password: OUnT17i/OgatVZCDu9xSUIRn566x/ojv5NBGgnOolAGZz+sB9PGXK6mbmUmtnBT5Sf3Y4w9Z3NUQUmo1H6Oe4w==
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPi2MeUBRahrFZgtNCU8rYdsADOJxnUJMsRV4pnZzXA2rgUI89ILgWiJx8kspbwWHg/kMTQZSZWgoVIaFvRuokCAwEAAQ==

---
## development environment setting
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mch?characterEncoding=utf-8
    username: root1
    password: OUnT17i/OgatVZCDu9xSUIRn566x/ojv5NBGgnOolAGZz+sB9PGXK6mbmUmtnBT5Sf3Y4w9Z3NUQUmo1H6Oe4w==
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPi2MeUBRahrFZgtNCU8rYdsADOJxnUJMsRV4pnZzXA2rgUI89ILgWiJx8kspbwWHg/kMTQZSZWgoVIaFvRuokCAwEAAQ==

---
## pressure environment setting
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mch?characterEncoding=utf-8
    username: root1
    password: OUnT17i/OgatVZCDu9xSUIRn566x/ojv5NBGgnOolAGZz+sB9PGXK6mbmUmtnBT5Sf3Y4w9Z3NUQUmo1H6Oe4w==
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPi2MeUBRahrFZgtNCU8rYdsADOJxnUJMsRV4pnZzXA2rgUI89ILgWiJx8kspbwWHg/kMTQZSZWgoVIaFvRuokCAwEAAQ==




# eureka client
#eureka:
#  client:
#    # 默认为30秒 从注册中心拉取服务时间间隔
#    # registry-fetch-interval-seconds: 5
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
